### ISSUE TITLE
Setting up ActiveStorage

### ISSUE THREAD

**Issue by kirillian** [kirillian/oil_change_reminder#2]
# Setup ActiveStorage
### Why ActiveStorage?
ActiveStorage is a Rails' native file storage solution that allows you to upload to S3, etc just like Paperclip, Refile, or Carrierwave which you may have used prior. However, Rails integrates with ActiveStorage a bit more smoothly and often is a bit less work out of the box.

### Instructions
Read more on ActiveStorage here: https://edgeguides.rubyonrails.org/active_storage_overview.html

Summary of instructions here (assuming you are in this project's directory):
```bash
bin/rails active_storage:install
bin/rails db:migrate
```

Make your `config/storage.yml` file (create if needed) look like the following:
```yaml
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>
```

We will come configure a production service like S3/GCM/Azure later in the process when pushing to Heroku

Add or edit the following lines to the following files:
`config/environments/development.rb`
```ruby
# Store files locally.
config.active_storage.service = :local
```

`config/environments/test.rb`
```ruby
# Store files locally.
config.active_storage.service = :test
```
